#!/usr/bin/env bash

switch_to() {
	if [[ -z $TMUX ]]; then
		tmux attach-session -t $1
	else
		tmux switch-client -t $1
	fi
}

has_session() {
	tmux list-sessions | grep -q "^$1:"
}

hydrate() {
	if [ -f $2/.tmux-sessionizer ]; then
		tmux send-keys -t $1 "source $2/.tmux-sessionizer" c-M
	elif [ -f $HOME/.tmux-sessionizer ]; then
		tmux send-keys -t $1 "source $HOME/tmux-sessioniser" c-M
	fi
}

if [[ $# -eq 1 ]]; then
	selected=$1
else
	selected=$(find \
		~/ \
		~/projects/ \
		~/nixos-dotfiles \
        ~/work \
        ~/documents \
		-mindepth 1 -maxdepth 1 -type d \
		-not -name '.git' \
		| fzf --color='info:#78a9ff,hl:#33b1ff,hl+:#33b1ff')
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
	tmux new-session -s $selected_name -c $selected
	hydrate $selected_name $selected
	exit 0
fi

if ! has_session $selected_name; then
	tmux new-session -ds $selected_name -c $selected
	hydrate $selected_name $selected
fi

switch_to $selected_name
