set -a terminal-features "tmux-256color:RGB"
set -g base-index 1
set -g renumber-windows on   
set -g mode-keys vi
set -g status-position top
set -g status-justify absolute-centre
set -g status-style "bg=default"
set -g window-status-current-style "fg=black bg=white  "
set -g status-interval 5
set -g status-left-length 35
set -g status-left "#S"
set -g status-right ""

bind -T copy-mode-vi y send -X copy-pipe-and-cancel "wl-copy"

bind -n C-f run-shell "tmux neww ~/.config/scripts/tmux-sessionizer"

# Utilities
bind u switch-client -T utilities
bind -T utilities s run-shell -b \
	"tmux set -g status-right '#(~/.config/scripts/elapsed.sh)'; \
	sleep 2; tmux set -g status-right ''"
bind -T utilities j run-shell \
	"tmux neww '~/.config/scripts/journal.sh'"

# todos
bind -T utilities t switch-client -T todos
bind -T todos o run-shell \
	"tmux neww '~/.config/scripts/project-todos.sh --open'"
bind -T todos n run-shell \
	"tmux neww '~/.config/scripts/project-todos.sh --new'"
bind -T todos a run-shell \
	"tmux neww '~/.config/scripts/project-todos.sh --open --all'"

# Web Bookmarks Manager
bind b switch-client -T bookmarks
bind -T bookmarks o run-shell \
	"tmux neww ~/.config/scripts/bookmarks.sh"

bind r source-file "~/.config/tmux/tmux.conf"
bind g run "~/.config/tmux/open-github.sh"

# Resizing
bind -r C-k resize-pane -U
bind -r C-j resize-pane -D
bind -r C-h resize-pane -L
bind -r C-l resize-pane -R

# Selection
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R
